services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: banco_talentos
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: